version: '3.8'

services:
  mysql:
    container_name: ortho-ai-mysql
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root_password 
      MYSQL_DATABASE: ortho_ai  
      MYSQL_USER: mysql 
      MYSQL_PASSWORD: docker
    volumes:
      - ./data/mysql:/var/lib/mysql

  cache: 
    container_name: ortho-ai-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data