name: Run E2E Tests

on:
  push:
    branches: [recovery-branch]
  pull_request:
    branches: [recovery-branch]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_USERNAME: mysql
          MYSQL_PASSWORD: root_password
          MYSQL_DB: ortho_ai
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create data directories
        run: |
          mkdir -p data/mysql

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Wait for MySQL
        run: |
          until mysqladmin ping -h 127.0.0.1 --silent; do
            echo "Waiting for MySQL to be ready..."
            sleep 5
          done

      - name: Run e2e tests
        run: npm run test:e2e
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          WEB_HOST: ${{ secrets.WEB_HOST }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY}}
          OPENAI_ORGANIZATION_ID: ${{ secrets.OPENAI_ORGANIZATION_ID }}
          OPENAI_PROJECT_ID: ${{ secrets.OPENAI_PROJECT_ID }}
          RUST_BACKTRACE: 1
